<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ganesh Thete_eye1563</name>
   <tag></tag>
   <elementGuidId>cde688be-5e6f-40ce-a7bc-b77eb180d49e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eye1563</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='eye1563']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8ca64520-b188-4fce-8782-9e470a319fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye</value>
      <webElementGuid>6d680eee-d813-40d1-bac4-896f559a5222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/AdminPhase4/LoanApplications/Details/1563?value=6690967&amp;status=Submitted</value>
      <webElementGuid>55854417-648e-4d40-8010-edda3237b652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eye1563</value>
      <webElementGuid>00b5a7ff-3fa1-4e0d-94da-de9f22e27973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:return LoadInDiv(this.href);</value>
      <webElementGuid>061244bc-a401-4cae-a064-70e2543dcd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eye1563&quot;)</value>
      <webElementGuid>9f47f7fb-5845-407f-b497-d8670e714af6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='eye1563']</value>
      <webElementGuid>7375874f-fc9e-44b9-9935-8bc99654a7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblEcomApplicaation']/tbody/tr/td[14]/i/a</value>
      <webElementGuid>93ee7414-e75e-4918-bf6b-6ba59a28ef70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/AdminPhase4/LoanApplications/Details/1563?value=6690967&amp;status=Submitted')]</value>
      <webElementGuid>122e7f9b-7ed7-46cb-8feb-6c86e6b5528e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i/a</value>
      <webElementGuid>a7e3cb3a-b8fd-4cfd-9439-789bc939a320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/AdminPhase4/LoanApplications/Details/1563?value=6690967&amp;status=Submitted' and @id = 'eye1563']</value>
      <webElementGuid>9b3111e5-7300-402c-a784-e9eefba51ccf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
