<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Submitted</name>
   <tag></tag>
   <elementGuidId>18177e6b-9860-4601-9469-3fd2007edeaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblEcomApplicaation']/tbody/tr/td[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1d71f6cb-34f8-4ba8-9a0a-bf50d02f60ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Submitted 
                </value>
      <webElementGuid>a61b813b-fd80-4e5d-98de-450b8fc2aeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblEcomApplicaation&quot;)/tbody[1]/tr[1]/td[9]</value>
      <webElementGuid>dac67652-69cb-46e0-a0e5-ae8289de3131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblEcomApplicaation']/tbody/tr/td[9]</value>
      <webElementGuid>95d6c885-9d77-441a-808a-47b9635d699b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R1106824600386'])[1]/following::td[5]</value>
      <webElementGuid>a34c636b-7161-4c6a-90e2-252ed457c070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganesh Thete'])[4]/preceding::td[4]</value>
      <webElementGuid>935f170d-b9b5-4bd5-861b-15c2f421ae11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESHNA'])[1]/preceding::td[9]</value>
      <webElementGuid>be1ace3c-bea2-45b9-8451-8ed9035fed65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submitted']/parent::*</value>
      <webElementGuid>8c0e79cb-317d-414e-a47a-e38e5096d03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]</value>
      <webElementGuid>1b63ce6b-fa6c-4a13-af5b-9e68a57de73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                    Submitted 
                ' or . = '
                    Submitted 
                ')]</value>
      <webElementGuid>0b18e379-a5ee-4199-bd52-7a1d9eb5b41d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
