<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_P</name>
   <tag></tag>
   <elementGuidId>edefb1cf-a585-4002-b2dd-5121df67ecba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rootReact']/section/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9353a1d6-7530-4297-9f10-835ef410f805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>a698b01c-3e5d-46f6-a03d-c3789a30e71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>20370192-eb4d-423b-a2a1-d8b1b5e841a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootReact&quot;)/section[@class=&quot;main-header-container&quot;]/div[@class=&quot;extra-card-wrapper&quot;]/div[@class=&quot;profileContainer&quot;]/div[1]/div[@class=&quot;pointer&quot;]</value>
      <webElementGuid>2017c437-9d31-4402-a5e9-ff285675cfdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rootReact']/section/div/div/div/div</value>
      <webElementGuid>6952ed28-ab73-4715-a714-b83b20dd81d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pratik Jain'])[1]/preceding::div[1]</value>
      <webElementGuid>c76c2cef-cb52-442c-9a18-85fe78b107f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>ef75b058-305c-4f9b-9a40-c08894fa083d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'P' or . = 'P')]</value>
      <webElementGuid>5c99b6da-cf1f-495b-8b20-648fbf8239f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
