<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_email</name>
   <tag></tag>
   <elementGuidId>43f8a61d-27f4-4b72-ad52-d2edb06e0381</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0da375c-9f21-4479-8248-9b7879f3848c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d6ee75f6-8743-4f82-b695-d5726ef4101b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>abe7ba8a-9bf6-4a8c-8c59-5d1bf3ccd47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Email Address</value>
      <webElementGuid>119c673b-e6f9-4622-8518-5b27a42db603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89f51988-5913-4e49-86d5-43e1aa561b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input css-mnn31</value>
      <webElementGuid>31c9db57-e6b3-4dfb-9de5-715e8c904bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootReact&quot;)/div[@class=&quot;login-main-card&quot;]/div[@class=&quot;login-right-container&quot;]/div[@class=&quot;login-container login-right-main&quot;]/form[@class=&quot;ant-form ant-form-horizontal gx-signin-form gx-form-row0&quot;]/div[@class=&quot;input-container email-div-input&quot;]/div[@class=&quot;MuiInputBase-root MuiInput-root MuiInput-underline MuiInputBase-colorPrimary MuiInputBase-fullWidth Mui-focused email-error css-18mr7wb&quot;]/input[@class=&quot;MuiInputBase-input MuiInput-input css-mnn31&quot;]</value>
      <webElementGuid>8b2f0f07-f682-4913-b7fb-f2fff7856c6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>d9d9c3c8-0e25-406b-846f-e6ef53674bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rootReact']/div/div[2]/div/form/div/div/input</value>
      <webElementGuid>47d53177-72f7-433e-80e4-c89df6433023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c898952c-91bb-4e2c-a14d-f9192eceeee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @placeholder = 'Enter Email Address' and @type = 'text']</value>
      <webElementGuid>2daf45a4-4b2e-4764-b2b6-570330d68001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
