<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add_mat-expansion-indicator ng-tns-c20_5a259f</name>
   <tag></tag>
   <elementGuidId>ec2f1275-e0dd-44b0-9c5b-a44f620b4590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-23']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mat-expansion-indicator.ng-tns-c205-162.ng-trigger.ng-trigger-indicatorRotate.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>198a5b2a-9476-435f-a011-8c1301cc3477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-expansion-indicator ng-tns-c205-162 ng-trigger ng-trigger-indicatorRotate ng-star-inserted</value>
      <webElementGuid>b45168dd-c7ff-4ca3-beb0-29e57de52b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-expansion-panel-header-23&quot;)/span[@class=&quot;mat-expansion-indicator ng-tns-c205-162 ng-trigger ng-trigger-indicatorRotate ng-star-inserted&quot;]</value>
      <webElementGuid>4b0d921f-43f0-4dc9-9af7-d1d9364048b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-23']/span[2]</value>
      <webElementGuid>aad81b17-ec9a-4b9e-8966-e1df1394f896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel[2]/mat-expansion-panel-header/span[2]</value>
      <webElementGuid>3e569e15-a72c-43da-b7cc-611d934bc7c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
