<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>8f277f80-5710-42c5-8223-39c18e2aad58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Add'])[1]/following::*[name()='svg'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.absolute.top-3.right-2.w-8.h-8.min-h-8.mat-icon-button.mat-button-base.ng-tns-c626-148.ng-star-inserted.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper > mat-icon.mat-icon.notranslate.icon-size-5.text-red-600.mat-icon-no-color > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>900908c1-6ea7-484f-b5de-17aa9cda3856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>1caa99f1-8c51-4a5c-bfc7-7b2cf014b924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b830a0e0-2c71-4c9a-adb9-145813211a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>21f1d576-fd69-40aa-a3ee-329c06dfd220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>d5c3ebac-c71a-4374-91b4-63cea013c505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>6ca87f45-2a1a-4338-9f7b-90660da81f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>a1546b4a-54ce-4a43-8a8f-0663f7d56889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preserveAspectRatio</name>
      <type>Main</type>
      <value>xMidYMid meet</value>
      <webElementGuid>00786f4c-9823-4651-b4a9-46208ae12425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d4b6071-cd40-4219-b114-9084130f5e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-23&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c204-161&quot;]/div[@class=&quot;space-y-4 ng-tns-c626-148 ng-star-inserted&quot;]/div[@class=&quot;relative p-4 border rounded ng-tns-c626-148 ng-star-inserted&quot;]/button[@class=&quot;mat-focus-indicator absolute top-3 right-2 w-8 h-8 min-h-8 mat-icon-button mat-button-base ng-tns-c626-148 ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/mat-icon[@class=&quot;mat-icon notranslate icon-size-5 text-red-600 mat-icon-no-color&quot;]/svg[1]</value>
      <webElementGuid>dd7e1ddc-5556-4710-aacc-57ab16c4322c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Add'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>7450506d-b1ed-467e-8d73-cc31ce144191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KYC / Identifiers'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>f78b3c62-511f-497e-a64b-6ea036fe32cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIC'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>b2f324a6-852d-4cf3-a3af-471d5d23704d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R0709944203629'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>24ee3c82-706a-4213-b637-d879313a3d3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
