<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next_in_Limit</name>
   <tag></tag>
   <elementGuidId>192f6125-4abc-4416-ab91-85f2078d5f30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-label[contains(text(),'Validity')]/ancestor::span/parent::div/parent::div/ancestor::mat-form-field/parent::div/following-sibling::div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
