<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Self Employed No PermitEmployment Type</name>
   <tag></tag>
   <elementGuidId>dd15f18f-9dbf-4083-9032-685ba1aed0db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-step-content-2-0']/form/fieldset/mat-form-field/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-flex.ng-tns-c32-254</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0b518453-20be-4bc7-a193-c9e91d71af41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-flex ng-tns-c32-254</value>
      <webElementGuid>3ede010b-6102-4368-bf03-d34528e98085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Self Employed No PermitEmployment Type</value>
      <webElementGuid>c77e8412-bfd8-4c86-baae-f6f730e0f014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-2-0&quot;)/form[@class=&quot;flex flex-wrap ng-star-inserted ng-untouched ng-pristine ng-valid&quot;]/fieldset[@class=&quot;flex flex-wrap w-full form-container&quot;]/mat-form-field[@class=&quot;mat-form-field form-fields ng-tns-c32-254 mat-primary mat-form-field-type-mat-select mat-form-field-appearance-fill mat-form-field-can-float mat-form-field-has-label ng-untouched ng-pristine ng-valid ng-star-inserted mat-form-field-should-float&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c32-254&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c32-254&quot;]</value>
      <webElementGuid>ad18fc9d-38d4-4836-bb92-26fe5913880b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-2-0']/form/fieldset/mat-form-field/div/div</value>
      <webElementGuid>3f816eb5-0a12-4629-9680-2884d0f71d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field/div/div</value>
      <webElementGuid>831abd15-c7cf-4f37-b5d6-938fc147a34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Self Employed No PermitEmployment Type' or . = 'Self Employed No PermitEmployment Type')]</value>
      <webElementGuid>0c05de0e-b615-4465-bab5-9f1a33d8abd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
