<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_industryAvg</name>
   <tag></tag>
   <elementGuidId>36303a1d-ed4f-46c7-b72e-259b3ecf3d22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[text()='Queries']/parent::button/ancestor::workflow-step-header/following-sibling::div[1]/div/app-credit-scorecard/div/div/app-scorcard-input-output/div[2]/div/ul/li[34]/div[contains(text(),'ind')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
