<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Not Applicable</name>
   <tag></tag>
   <elementGuidId>b1003546-3a28-4df3-9c82-69989a46267d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-59']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-59</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a0ce767-f85d-41d1-80a5-0c4bc5673e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c88-264</value>
      <webElementGuid>d880111e-0d82-46b9-8636-eed30f90af91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-59</value>
      <webElementGuid>3bd32763-d1be-4381-a7c2-4df54c8f62cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Applicable</value>
      <webElementGuid>35a99f21-8bb4-4873-af4e-61c5ea952f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-59&quot;)</value>
      <webElementGuid>bf65def9-da8f-497c-9370-b41a24b47ce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-59']</value>
      <webElementGuid>50bccad1-5634-4e96-a679-1a40fb5c59c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-58']/div/div</value>
      <webElementGuid>1bec5bd5-0731-4d6d-9873-67c6c845e4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Years in Occupation'])[1]/following::div[11]</value>
      <webElementGuid>17edab94-92c6-49a9-98f0-a953f6124419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sector'])[1]/following::div[20]</value>
      <webElementGuid>a6b359ba-9c0d-4e1a-80ab-77990398d288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Type'])[1]/preceding::div[3]</value>
      <webElementGuid>7c018343-d26d-424d-82c5-ee9d5d6e3b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[6]/div/div/div/div/div/mat-select/div/div</value>
      <webElementGuid>fa2ad3c0-d20d-4c4c-8ea9-7e032b1ffc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-59' and (text() = 'Not Applicable' or . = 'Not Applicable')]</value>
      <webElementGuid>b6fd8c25-a9e1-47f7-9e3d-432661584590</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
