<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_other</name>
   <tag></tag>
   <elementGuidId>8494f0a2-fe86-455e-8ec1-ed30d5201d65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[text()='Queries']/parent::button/ancestor::workflow-step-header/following-sibling::div[1]/div/app-credit-scorecard/div/div/app-scorcard-input-output/div[2]/div/ul/li[28]/div[contains(text(),'oth')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
