<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat_ArrowEmpDetails</name>
   <tag></tag>
   <elementGuidId>6004e834-e84d-4f68-8053-19b646181e85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-label[contains(text(),'Employment')]/ancestor::span/parent::div/div/div/mat-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
