<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Employed Full Time</name>
   <tag></tag>
   <elementGuidId>6031daac-2b5f-4705-b73a-829c9c4f68f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-5655 > span.mat-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-5655']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b0cf6a7-2026-4000-afe2-664039831b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>7bd26ca0-84e1-43eb-80db-527d053a7dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employed Full Time</value>
      <webElementGuid>b70b1545-7e3c-4812-a01f-074d6bbb6c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-5655&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>4705d634-68ba-402e-95ba-7643b7fe5509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-5655']/span</value>
      <webElementGuid>de2e9ecd-5531-46ab-a87a-2ea83fa08abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employed Contractual'])[1]/following::span[1]</value>
      <webElementGuid>4fa99261-7f81-4dc6-ac60-0c735a9b6dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FEB 2024'])[1]/following::span[2]</value>
      <webElementGuid>8159b93f-8784-4d05-898f-6b9f1d6d28bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employed Part Time'])[1]/preceding::span[1]</value>
      <webElementGuid>dbb9b1e6-8f11-4785-a9b2-c4ce24888399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self Employed No Permit'])[1]/preceding::span[2]</value>
      <webElementGuid>8422d1bc-26aa-4546-95ee-acafabf47d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employed Full Time']/parent::*</value>
      <webElementGuid>59ccf2d0-bedc-48a9-a679-1a04ba7fcc14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]/span</value>
      <webElementGuid>bae71b79-b031-4ca8-ab4d-41ce6f78686c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Employed Full Time' or . = 'Employed Full Time')]</value>
      <webElementGuid>1ccf07d0-2d1a-4b1f-8718-aa7e21867e8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
