<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>7cd234f0-368b-4d1e-b859-032da8ff8e21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-36']/span/mat-panel-description/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.flex.items-center.h-full.text-md.ng-tns-c539-545.text-primary.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7f68c83-5028-45b0-9c72-0d4e96bfdf34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center h-full text-md ng-tns-c539-545 text-primary ng-star-inserted</value>
      <webElementGuid>5e0e29c0-453c-47dd-a177-6fd83fc96d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> +Add </value>
      <webElementGuid>585fcef5-40a1-4de8-9902-002965631b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-expansion-panel-header-36&quot;)/span[@class=&quot;mat-content ng-tns-c205-556&quot;]/mat-panel-description[@class=&quot;mat-expansion-panel-header-description ng-tns-c205-556&quot;]/button[@class=&quot;flex items-center h-full text-md ng-tns-c539-545 text-primary ng-star-inserted&quot;]</value>
      <webElementGuid>110f24dd-034f-4ebe-b519-14830f35f696</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-36']/span/mat-panel-description/button</value>
      <webElementGuid>acc526f9-a921-45e9-b561-78f1c1660dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Addresses'])[1]/following::button[1]</value>
      <webElementGuid>ff7ffaf4-1fd0-4092-bad2-f48eb1f2fd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Essential Information'])[1]/following::button[1]</value>
      <webElementGuid>6dcfd72a-e807-43a8-981b-7c59567bfbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No addresses available for this client'])[1]/preceding::button[1]</value>
      <webElementGuid>fa9fff0c-e970-4633-9991-a663a6870cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KYC / Identifiers'])[1]/preceding::button[1]</value>
      <webElementGuid>69033e85-a8ac-40d8-971b-dec8374aedc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+Add']/parent::*</value>
      <webElementGuid>e92023ac-a6e8-416b-9691-60a74edf50e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-panel-description/button</value>
      <webElementGuid>f769e4f7-0a7d-4a79-9505-5100f2e5dbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' +Add ' or . = ' +Add ')]</value>
      <webElementGuid>c2136337-1bbe-43b2-b0a0-e1f1a0fad8d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
