<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Loan Accounts</name>
   <tag></tag>
   <elementGuidId>c5457198-7621-431b-b83a-949bc82bf1a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-tab-label-7-1']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-tab-label-7-1 > div.mat-tab-label-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e82e830e-5836-4a13-8d30-906665c34ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-tab-label-content</value>
      <webElementGuid>e4f4ccc8-c9e8-4527-81b8-bb80ca2f4463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan Accounts</value>
      <webElementGuid>3b5a3b39-dbab-418f-b6c5-bf9fd3b287fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-label-7-1&quot;)/div[@class=&quot;mat-tab-label-content&quot;]</value>
      <webElementGuid>831e1a8f-dc76-45b9-9a8c-ef88e04b97f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-tab-label-7-1']/div</value>
      <webElementGuid>eb7f6fae-e0c2-4def-9391-626f90861ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Applications'])[2]/following::div[2]</value>
      <webElementGuid>28dbb651-9140-4b6e-b136-cb9cb0444fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::div[12]</value>
      <webElementGuid>39cd09cc-7ce5-47a4-8804-ce886b0e5d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BNPL/CC'])[1]/preceding::div[2]</value>
      <webElementGuid>171992e4-f282-4750-a0b3-d4163135b00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Virtual Credit Line'])[1]/preceding::div[4]</value>
      <webElementGuid>0d903091-16e8-47d1-99fa-0911a0dafe25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Loan Accounts']/parent::*</value>
      <webElementGuid>d9e0bd49-5f16-42d0-91b8-6911671ef7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tab-header/div[2]/div/div/div[2]/div</value>
      <webElementGuid>0acfb1a8-f5bf-416a-bb87-bea231994bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Loan Accounts' or . = 'Loan Accounts')]</value>
      <webElementGuid>bea42380-5bc4-4051-879f-2aff4618de96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
