<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Last Name_mat-select-arrow ng-tns-c88-21</name>
   <tag></tag>
   <elementGuidId>3ab1f760-539d-4391-865c-dc8bef6bdb6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-label[text()='Gender']/ancestor::span/parent::div/mat-select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow.ng-tns-c88-21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>727dcff6-a349-4c6d-b5dc-03ae025fa37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow ng-tns-c88-21</value>
      <webElementGuid>bef78c7f-5331-44e0-a20d-dd7a09e195f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-4&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c88-21&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c88-21&quot;]/div[@class=&quot;mat-select-arrow ng-tns-c88-21&quot;]</value>
      <webElementGuid>fa90e071-74b7-4489-9db6-f823ddc54306</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-4']/div/div[2]/div</value>
      <webElementGuid>419ca60d-e2ad-45f4-8f76-c2277af46efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[4]/div/div/div/mat-select/div/div[2]/div</value>
      <webElementGuid>9e3658be-11ea-46c0-b73e-aa8747c8f4b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
