<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Day_mat-select-value-131</name>
   <tag></tag>
   <elementGuidId>921d3b9e-bdea-4816-b6ea-543ecdd657e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-131']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-131</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8a6d9c0d-4179-4e0e-be24-e6435c40bf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c88-601</value>
      <webElementGuid>07ac39bc-16fb-49ad-acfb-be5b8b7db6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-131</value>
      <webElementGuid>555ea6dc-b8df-4077-b226-98763ee81030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-131&quot;)</value>
      <webElementGuid>60d55eee-f3ba-4e9a-9cb7-e6b89898bd37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-131']</value>
      <webElementGuid>b671d692-f92a-4fb2-bbb8-66b5fbfe1d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-130']/div/div</value>
      <webElementGuid>c72c4584-333a-4eb1-ad83-0599cc89f743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day'])[2]/following::div[7]</value>
      <webElementGuid>3c150411-e689-4a51-88da-45171d95c72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom'])[2]/following::div[9]</value>
      <webElementGuid>da04dffe-39b5-42fe-b121-ccd9bbd6afe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicable Charges'])[1]/preceding::div[18]</value>
      <webElementGuid>5b4e2c02-01c6-42e6-a033-94c8f3af7575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Based Charges'])[1]/preceding::div[19]</value>
      <webElementGuid>f674ce5c-1865-4824-b063-516faad8442a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/div[2]/div[2]/div[2]/div/mat-form-field/div/div/div/mat-select/div/div</value>
      <webElementGuid>f9074a83-abac-4df4-8bc3-ebcb974c8dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-131']</value>
      <webElementGuid>53163977-6c05-4912-ad1f-74da96ec7859</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
