<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_External ID_mat-select-value-101</name>
   <tag></tag>
   <elementGuidId>42580542-da79-486c-8a8e-1c9850ae82af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-101']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-101</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>95731532-57d8-4ee4-b8f3-9d4ad3a44731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c88-448</value>
      <webElementGuid>5d5ded6d-f956-44dc-b562-a5f7fb856fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-101</value>
      <webElementGuid>25ca9cd3-8aa4-4a80-892a-7d568adf1f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-101&quot;)</value>
      <webElementGuid>1eb00cf2-44d4-4756-984c-47471ef80d0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-101']</value>
      <webElementGuid>76e90be6-0512-493d-acdf-c971abcd91b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-100']/div/div</value>
      <webElementGuid>ac16531a-686f-4047-beb8-4bb35f5f4773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='External ID'])[1]/following::div[10]</value>
      <webElementGuid>44d75ac0-c8b6-4edb-9141-28f6dcf6e895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Would you like to add advance details?'])[1]/following::div[21]</value>
      <webElementGuid>ee41c512-7bb0-4dd2-9448-b683da4d77e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Type'])[1]/preceding::div[3]</value>
      <webElementGuid>72766624-875a-49a5-b9e7-4c3a896855cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Classification'])[1]/preceding::div[11]</value>
      <webElementGuid>b2d1e2f2-9ac4-4c2e-a315-f5882f2c3c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div[2]/mat-form-field/div/div/div/mat-select/div/div</value>
      <webElementGuid>4d93a5b0-5436-48ff-8a03-fcc45bf1d336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-101']</value>
      <webElementGuid>93234e49-c670-4b38-9f2d-0c60063f1c30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
