<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Day_mat-select-value-125</name>
   <tag></tag>
   <elementGuidId>4373f84d-a1e5-497c-a3c3-d4696d62df3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-125']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-125</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5af63d49-d55e-46d4-b957-885d7161c52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c88-594</value>
      <webElementGuid>058d2067-84ec-406e-9585-7f0479adbc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-125</value>
      <webElementGuid>94c47b3c-b22e-4451-9db4-91ffdbcc3eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-125&quot;)</value>
      <webElementGuid>e61dd8b4-28dc-4dc4-8e54-ad8524941a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-125']</value>
      <webElementGuid>f9b40b7b-6c56-4e87-8e27-1c1017fec2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-124']/div/div</value>
      <webElementGuid>0596b106-56e7-49ae-834c-c5e5384c30a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day'])[1]/following::div[7]</value>
      <webElementGuid>8923ffb3-6265-4caa-abaa-ab4cbcc5732a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom'])[1]/following::div[9]</value>
      <webElementGuid>544ceefd-f976-4c2f-9093-5925cf0133bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Day'])[1]/preceding::div[18]</value>
      <webElementGuid>b8823088-e606-44a1-aeb8-eac5c6f2cc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/mat-form-field/div/div/div/mat-select/div/div</value>
      <webElementGuid>61b1456b-9bfa-4f29-8cf6-c62fbd1924e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-125']</value>
      <webElementGuid>8f274211-b83b-4768-a718-620bb551721f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
