<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_first_mat-select-value-127</name>
   <tag></tag>
   <elementGuidId>25682a54-409d-40d5-a9f6-2313726f936d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-127']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-127</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4cc235a5-fbc9-4ab0-88ad-f78ebe0e960b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c88-596</value>
      <webElementGuid>cbb0fd35-0cda-434a-a0c5-103e5051c27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-127</value>
      <webElementGuid>7a257f9c-f033-4bfb-b68f-b730be8f74f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-127&quot;)</value>
      <webElementGuid>1a73ea7c-cf8f-40d6-9c05-b8ccfa6fabb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-127']</value>
      <webElementGuid>e3ad759f-e195-4e14-8939-6a4b740c19d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-126']/div/div</value>
      <webElementGuid>0fb144ac-5429-44da-9de7-ec808557802e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='first'])[1]/following::div[11]</value>
      <webElementGuid>2a64d8db-d6d1-4bf3-a606-a2f2593f588f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day'])[1]/following::div[18]</value>
      <webElementGuid>11dbd4d0-014c-4fd4-8041-c6e2939a672b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Day'])[1]/preceding::div[7]</value>
      <webElementGuid>d9b2891a-005f-4fb6-aa3f-12dd2989187d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/mat-form-field[2]/div/div/div/mat-select/div/div</value>
      <webElementGuid>bf693052-bc6f-45cd-b6f6-3ff15d5aa9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-127']</value>
      <webElementGuid>c4b4f6a9-702e-4e13-977b-f8b8a1bb90cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
