<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_The amount must be between 1500 and 5_0a88dd</name>
   <tag></tag>
   <elementGuidId>a89cca03-7451-4b69-bd07-fe4b39641cc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-79']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-79</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>310e7920-6916-400e-8aa4-d08c8ecf2e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control mat-datepicker-input ng-tns-c32-588 cdk-text-field-autofill-monitored ng-touched ng-dirty ng-valid</value>
      <webElementGuid>cde118aa-bdc5-41ed-b49c-9d4f4790a9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-79</value>
      <webElementGuid>84629ffc-b4a8-4fed-adbe-55d0672c1cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>478d71f0-cd7b-4730-b332-9a83947b0f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>486e0532-c1ad-4533-9281-06d47400733d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2024-01-24T17:30:33+05:30</value>
      <webElementGuid>4b014fcb-e588-4f1b-aa52-a8dcfd4575ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-calendar</name>
      <type>Main</type>
      <value>mat-datepicker-28</value>
      <webElementGuid>5c9d87e8-afd7-4765-abc1-d7eb40a6eb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2600d75b-a22d-48ab-842f-7cf76abd1374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-79&quot;)</value>
      <webElementGuid>cb802582-3019-4a27-b737-fa9d935e7c3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-79']</value>
      <webElementGuid>db3beb71-7402-48fb-8a49-ca65cf38943b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-1-0']/div/form/mat-form-field[3]/div/div/div/input</value>
      <webElementGuid>57de6006-01cf-4983-a0fa-5f28893d4769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/form/mat-form-field[3]/div/div/div/input</value>
      <webElementGuid>1749a0a1-ec12-4249-9877-20b58bc49ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-79']</value>
      <webElementGuid>c22dd29c-361f-440c-8e8b-6797e6206de0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
