<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View  Verify</name>
   <tag></tag>
   <elementGuidId>4822a0eb-8162-4783-9854-6a0331bc38c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1606</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='1606']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71082cab-b3ec-4a4d-a3f6-a37a412ba3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>bbfab558-ff3a-4273-b926-457790bb06ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clsView anchorDetail</value>
      <webElementGuid>c32defab-c2ea-4a13-8a5e-99aefabfa324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1606</value>
      <webElementGuid>f25eddef-c6f1-4137-8f34-caaaedd8f550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>FileUploadsForLoanApp\e75db37d-9688-47ae-8797-ee66e55cd46a.pdf</value>
      <webElementGuid>4dd73d96-d754-4c24-afa6-613c8abb0a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View &amp; Verify</value>
      <webElementGuid>d49d3425-3bb9-4909-a2e1-8740ec24c88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1606&quot;)</value>
      <webElementGuid>03fb60fe-6106-49ad-8aa7-07d8627fa168</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='1606']</value>
      <webElementGuid>a4ae0cf5-f8a3-400b-8a92-a6aabf32a2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='docRow_1606']/td[5]/a</value>
      <webElementGuid>54f64d07-472c-41be-a129-59f1dfb16118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View &amp; Verify')]</value>
      <webElementGuid>1d5598f1-47b3-4515-bef3-44c59cb37148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Docs verification in progress'])[1]/following::a[1]</value>
      <webElementGuid>a34902a5-741b-4215-8233-758efd895d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utility bill or Bank Statement'])[1]/following::a[1]</value>
      <webElementGuid>701906f8-59cc-4844-8626-b9a4aebae7e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salary Slip'])[1]/preceding::a[1]</value>
      <webElementGuid>b5c934f3-bc64-4c6e-b477-6fb6a2155461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Docs verification in progress'])[2]/preceding::a[1]</value>
      <webElementGuid>7749c652-fc52-4fca-9617-63c4fd524518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View &amp; Verify']/parent::*</value>
      <webElementGuid>0b4e613c-8ef0-4615-b28f-2380bbcd5854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[2]</value>
      <webElementGuid>7509e94d-8a8c-4595-8c5f-4ef4eaabca11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>0d646570-ce25-491e-a470-d1d4f7c7348e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = '1606' and (text() = 'View &amp; Verify' or . = 'View &amp; Verify')]</value>
      <webElementGuid>8ad7c3b4-a0de-4763-840a-1cea302e2cc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
