<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit_1</name>
   <tag></tag>
   <elementGuidId>fa3bd294-a8d7-4689-9e55-6a733d6e4dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#docuSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='docuSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>78d1287a-e929-424e-ad5b-ecde48712bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c999fb17-df1e-4f39-854f-ec0cb8209f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary primaryButton</value>
      <webElementGuid>d01c9323-f265-4a57-9b8e-02c2397dc841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>docuSubmit</value>
      <webElementGuid>7f8758ea-01a6-4afb-9817-be3a01d4f10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>9ef27d33-bedb-4fdf-a32d-3a3568b675c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;docuSubmit&quot;)</value>
      <webElementGuid>f4b29bb9-3cb8-4a4c-821a-39aa63449020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='docuSubmit']</value>
      <webElementGuid>70877217-0906-40d5-aa48-d6e697339c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idDocStatusDiv']/div/div[3]/div/button</value>
      <webElementGuid>fe0172c6-0f07-4db8-9260-0168b0a2e461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please add remarks'])[1]/following::button[1]</value>
      <webElementGuid>232548e3-2bfd-4385-9015-ea00b03aa61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remark'])[3]/following::button[1]</value>
      <webElementGuid>565b5de0-31aa-4db6-a090-aad36133b4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver 1.0.0.3'])[1]/preceding::button[1]</value>
      <webElementGuid>f2fd23a4-5306-41db-9e3a-249055170719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected:'])[1]/preceding::button[1]</value>
      <webElementGuid>cc9b4370-ea9a-4f75-9443-ed3b51718b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>d1d444ec-3471-4b7f-9860-3e8ce9bd00af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/button</value>
      <webElementGuid>7b9a22db-7de2-4d4a-a2ce-18857a3a0f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'docuSubmit' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>1361b0c0-574a-40fd-b55f-8ba533c79f77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
