<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remark_docRemarkId_2</name>
   <tag></tag>
   <elementGuidId>df32eabf-e495-4f81-8a1d-ce316c356221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#docRemarkId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='docRemarkId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d502230f-936f-4f75-ae61-2e0c8a5fd869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control clstxt</value>
      <webElementGuid>f7a7ae2c-f47a-44e2-934f-08bcf4426059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>docRemarkId</value>
      <webElementGuid>87e96bd4-143d-4e73-90b5-23643c345f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>docRemarkId</value>
      <webElementGuid>ac736441-6048-40d0-b761-f49be0c2b54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;docRemarkId&quot;)</value>
      <webElementGuid>8b59b01e-3782-4f29-aabd-437fd8b21fee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='docRemarkId']</value>
      <webElementGuid>3a5cd3ed-40b2-4183-92c7-0330aae47cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idDocStatusDiv']/div/div[2]/div/div[2]/textarea</value>
      <webElementGuid>22455a3a-947f-4a24-9147-97c77899c59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/textarea</value>
      <webElementGuid>aba0115b-770b-4f6c-90a1-0ccaa6e6231c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'docRemarkId' and @name = 'docRemarkId']</value>
      <webElementGuid>5bbba0f1-7a6b-4640-8ea4-b73806c977a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
