<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Min Amt_min</name>
   <tag></tag>
   <elementGuidId>5544f358-c9ba-4614-9320-b0bc3d6d57dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#outlined-adornment-weight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='outlined-adornment-weight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8055bafe-d176-4382-b945-1d545e1f54e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outlined-adornment-weight</value>
      <webElementGuid>9136f653-c64d-46d6-afdc-d4e212e24149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>min</value>
      <webElementGuid>cd96c17f-fd9f-4638-b0e7-3ee8b288fa8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>09f481d2-a197-4282-afa1-a41223ecfcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8308fd47-104f-49a2-a25a-951e41c8c513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1x5jdmq</value>
      <webElementGuid>95838033-8012-4bb9-83b3-fec084322c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;full-layout fuse-splash-screen-hidden light theme-default&quot;]/div[@class=&quot;MuiDrawer-root MuiDrawer-modal MuiModal-root css-y28f86&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation16 MuiDrawer-paper MuiDrawer-paperAnchorRight css-1ab2xsx&quot;]/div[@class=&quot;MuiBox-root css-10d1q5i&quot;]/div[@class=&quot;payment-div&quot;]/div[@class=&quot;transaction-amount-div&quot;]/div[@class=&quot;transaction-amount-sub-div&quot;]/div[@class=&quot;transaction-amount-sub-div-input&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary Mui-focused css-1v4ccyo&quot;]/input[@id=&quot;outlined-adornment-weight&quot;]</value>
      <webElementGuid>7e25f0b1-6140-49be-a420-8282eec961da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='outlined-adornment-weight']</value>
      <webElementGuid>3c1b8bee-d19d-4584-a701-f3e421db3e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d6aa0fc3-ad48-443c-b7a8-d4be632557a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'outlined-adornment-weight' and @name = 'min' and @placeholder = 'Enter' and @type = 'text']</value>
      <webElementGuid>f5b9f6a2-8e3b-46c8-89ef-71002c291954</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
