<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__reEnter_acc_no</name>
   <tag></tag>
   <elementGuidId>5fcfbee2-7a87-4d5b-85a0-1fa47accf219</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reEnter_acc_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reEnter_acc_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b0b5dcd-066c-4b38-9df9-53cf6638c921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>68970cd2-9b9c-4048-819c-fa03a0cd85ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-untouched cdk-text-field-autofill-monitored ng-star-inserted ng-dirty ng-valid</value>
      <webElementGuid>f6773fc8-0359-4cb7-9519-d5411eaf6c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>423c5526-b63e-4db5-930f-51805f3d40f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reEnter_acc_no</value>
      <webElementGuid>e9689793-78f0-46cb-8dbf-86c4f81bff3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8f3dfef8-97e4-4c70-9389-888e64d9b798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>85d55ce0-4f90-4e7a-a5f1-ebd245fdfd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reEnter_acc_no&quot;)</value>
      <webElementGuid>f0fab984-94fa-4654-bdee-6bc98de8c3d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reEnter_acc_no']</value>
      <webElementGuid>9dc3e4a5-18d1-4b34-ba70-169ae42f6d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dynamicComponentParent']/source-details/div/div/div/app-update-source-detail/div/div/form/div/div[3]/mat-form-field/div/div/div/input</value>
      <webElementGuid>da826c21-5fa1-4be2-aa85-bb3914b0a161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/mat-form-field/div/div/div/input</value>
      <webElementGuid>7b955b70-48e0-4225-93dd-25c97a048bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'reEnter_acc_no']</value>
      <webElementGuid>2957b1e6-d7a8-46ca-9c02-505d843f1c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
