<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Max Amt_max</name>
   <tag></tag>
   <elementGuidId>91df84ea-fd8e-4985-b7ae-fe6c443d41c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.Mui-focused.css-1v4ccyo > #outlined-adornment-weight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='outlined-adornment-weight'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdca09f2-0597-41ae-94e6-c2ccb466a0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outlined-adornment-weight</value>
      <webElementGuid>9f6ae270-b785-49c8-b98c-7ebf83e7c900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>max</value>
      <webElementGuid>0f303ffe-1130-4746-89fd-0eae60b0979f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>902aedd8-cf1d-4d24-b162-0eea8c25ef85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>feb63d81-83d1-46ed-8760-1b87e122d07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1x5jdmq</value>
      <webElementGuid>0168e215-a2be-48de-8d9d-96a759613097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;full-layout fuse-splash-screen-hidden light theme-default&quot;]/div[@class=&quot;MuiDrawer-root MuiDrawer-modal MuiModal-root css-y28f86&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation16 MuiDrawer-paper MuiDrawer-paperAnchorRight css-1ab2xsx&quot;]/div[@class=&quot;MuiBox-root css-10d1q5i&quot;]/div[@class=&quot;payment-div&quot;]/div[@class=&quot;transaction-amount-div&quot;]/div[@class=&quot;transaction-amount-sub-div&quot;]/div[@class=&quot;transaction-amount-sub-div-input&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary Mui-focused css-1v4ccyo&quot;]/input[@id=&quot;outlined-adornment-weight&quot;]</value>
      <webElementGuid>fa229852-e3e5-4395-b4ca-7458c9baaf0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='outlined-adornment-weight'])[2]</value>
      <webElementGuid>2e291622-f270-49d4-816f-b7e8de9df164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>2a2f24a8-d165-4ce0-96fb-d82f25344bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'outlined-adornment-weight' and @name = 'max' and @placeholder = 'Enter' and @type = 'text']</value>
      <webElementGuid>156b84e2-aa08-4356-833c-08e5dfda4ad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
