<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Payment Method are not added yet Ad_e3e642</name>
   <tag></tag>
   <elementGuidId>5d0e4c14-6f88-4a91-9bd9-345e925d8845</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section.fee-details-table-no-fee-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rootReact']/section[2]/div/div/div/div[2]/div/div[3]/div[2]/div[2]/section/section</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>81fbefdc-65c4-490e-acac-57e839bd9997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fee-details-table-no-fee-container</value>
      <webElementGuid>91eaae98-4db2-4b27-b411-6bd6cefffca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment Method are not added yet+ Add Payment Method</value>
      <webElementGuid>1d5cef44-402d-45e7-8618-6ab695df6cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootReact&quot;)/section[@class=&quot;main-app-container&quot;]/div[@class=&quot;app-container&quot;]/div[1]/div[@class=&quot;ant-card merchant-onboarding ant-card-bordered&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-tabs ant-tabs-top ant-tabs-line&quot;]/div[@class=&quot;ant-tabs-content ant-tabs-content-animated ant-tabs-top-content&quot;]/div[@class=&quot;ant-tabs-tabpane ant-tabs-tabpane-active&quot;]/div[@class=&quot;ant-card-body screen-height-container&quot;]/section[@class=&quot;fee-details-table-container&quot;]/section[@class=&quot;fee-details-table-no-fee-container&quot;]</value>
      <webElementGuid>632a20e0-0619-4ac9-b681-4c270cc09a07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rootReact']/section[2]/div/div/div/div[2]/div/div[3]/div[2]/div[2]/section/section</value>
      <webElementGuid>f85d1537-0cd2-4a75-ab80-8f4d15d44253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Payment Method'])[1]/following::section[2]</value>
      <webElementGuid>3d25d9f9-41e8-4405-93ea-6a7f306ecff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Over'])[1]/following::section[2]</value>
      <webElementGuid>5dd3e295-3c3d-4427-83fc-9c25709d0d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/section</value>
      <webElementGuid>9e53ca9b-8e73-43ce-8124-ce18273fb21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Payment Method are not added yet+ Add Payment Method' or . = 'Payment Method are not added yet+ Add Payment Method')]</value>
      <webElementGuid>ab015b21-d4b5-40d6-a052-418d0cd15384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
