<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__mat-select-value-7</name>
   <tag></tag>
   <elementGuidId>a1a19848-61c6-4f22-97a0-b92ec7ca9a3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>109e8235-2fc4-488d-8bf6-20c3591b4bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c90-13</value>
      <webElementGuid>384ffec9-33db-42d9-9101-778eb45c2958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-7</value>
      <webElementGuid>f51b3c9d-8ca5-4b9a-81f1-74d803bdb469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-7&quot;)</value>
      <webElementGuid>3a3ee4ca-fff8-4c14-994c-6e9a507dd2fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-7']</value>
      <webElementGuid>d8fd716b-2060-4103-b1c9-95d8bfeddfb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-6']/div/div</value>
      <webElementGuid>b2f3f429-e0e9-4a3a-825f-66b7c1e0f23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::div[10]</value>
      <webElementGuid>961d7df5-c5d1-4f22-a736-71ff2c27e98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Line 1'])[1]/following::div[10]</value>
      <webElementGuid>1dec9a7e-b5e8-4319-a3fd-8cd9cf44335f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District'])[1]/preceding::div[3]</value>
      <webElementGuid>0bffb8fa-e0bd-4f79-a3ed-045de9aa2b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::div[3]</value>
      <webElementGuid>10d641c4-a3ee-4168-9497-d22b4ac11242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/mat-form-field/div/div/div/mat-select/div/div</value>
      <webElementGuid>01d976a7-25ea-479d-b929-2ebac16118cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-7']</value>
      <webElementGuid>53f4fe89-be45-4113-9e41-92f2c3089fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
