<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__mat-select-value-5</name>
   <tag></tag>
   <elementGuidId>77f25a9a-ad57-489d-af45-6bfa7a4accb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f82b1064-e876-49f1-a398-c561a74a3fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c90-10</value>
      <webElementGuid>18ec952c-63a5-4e21-94c8-0c30e99be306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-5</value>
      <webElementGuid>d531ac95-8193-4494-bce3-6ab8e08a294c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-5&quot;)</value>
      <webElementGuid>7d3e9476-54ec-4a84-82ee-2bb6973de9d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-5']</value>
      <webElementGuid>2fb94588-6093-4e74-a62f-4b9b0ad10141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-4']/div/div</value>
      <webElementGuid>94e76a67-9311-4a46-a50b-57e76e5be589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[10]</value>
      <webElementGuid>5a9ad44f-bb17-4f9a-a0da-a1c66847a3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::div[10]</value>
      <webElementGuid>58de1367-6a9e-471d-9be0-f9d82c557e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country Code'])[1]/preceding::div[3]</value>
      <webElementGuid>bec9da0b-3cad-4f0f-9d7e-8d56360b464d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::div[3]</value>
      <webElementGuid>370c0801-08e9-41f2-92f3-ad94fe661cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/mat-form-field/div/div/div/mat-select/div/div</value>
      <webElementGuid>9426aabd-9a93-42b2-b933-7c6e0b83a879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-5']</value>
      <webElementGuid>5f7dc6d6-189a-4e97-aa35-bd9cdd100375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
